runtime: nodejs22

# App Engine configuration for PeerJS server
service: peerjs-server

# Instance configuration
instance_class: F2  # Flexible environment instance class
automatic_scaling:
  min_instances: 1  # Keep at least 1 instance running for WebRTC signaling
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Environment variables
env_variables:
  NODE_ENV: production
  PEERJS_KEY: dulaan-peerjs-production-key
  ALLOW_DISCOVERY: "false"  # Disable peer discovery for security

# Network configuration
network:
  session_affinity: true  # Important for WebSocket connections

# Health check configuration
readiness_check:
  path: "/_ah/health"
  check_interval_sec: 10
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/_ah/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Resource limits
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10